.dockerignore
.gitignore
Dockerfile
LICENSE
Makefile
README.md
cmd/main.go
cmd/res/configuration.toml
cmd/res/docker/configuration.toml
cmd/res/sample-binary-device.yaml
cmd/res/sample-json-device.yaml
cmd/res/sample-numbers-device.yaml
driver/restdriver.go
driver/resthandler.go
driver/resthandler_test.go
go.mod
version.go

Create new REST device service which allows simple POSTing of data to the REST path /device/{deviceName}/{resourceName}
Supports all ValueType's 
Commanding and AutoEvents not implemented. Will be considered when use case identified.
See README for more details

feat(REST DS): Implement new REST Device service

---

README.md

RETS path chnaged to /ap1/vi/resource/{deviceName}/{resourceName}
Signed-off-by: lenny <leonard.goodell@intel.com>

Update README for change in REST path

---

Attribution.txt
Makefile
README.md
bin/test-attribution-txt.sh
bin/test-go-mod-tidy.sh
go.mod

Use released SDK.
Update makefile's test raget to follow standar set by edgex-go.
Add Attibution.txt file
Add Test/Simulation section to README.
closes #3

build(go.mod/makefile): Update to released SDK version, add make test target & update README

---

Dockerfile
Dockerfile.build
Jenkinsfile
go.mod

Updated appropriate files to switch to Go 1.13
closes #11

build: Switch to Go 1.13

---

cmd/main.go

Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

fix: Update package name in main.go to match the one in version.go

---

snap/hooks/configure
snap/hooks/install
snap/hooks/pre-refresh
snap/snapcraft.yaml

Adds the snapcraft files for device rest
Signed-off-by: adam-w-mitchell <adam.w.mitchell@intel.com>
Issue Number:
N/A 
This PR adds the snap files to create snaps for device rest
No
Run 'snapcraft' to create the snap for device-rest.

feat(device-rest): Add snap directory for device-rest

---

Dockerfile

Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
Issue Number:
https://github.com/edgexfoundry/device-rest-go/issues/34

refactor: update dockerfile to appropriately use ENTRYPOINT and CMD, closes#34

---

Dockerfile
Dockerfile.build
Jenkinsfile
bin/test-attribution-txt.sh
go.mod
snap/snapcraft.yaml

fix #38 
Signed-off-by: Chris Hung <chris@iotechsys.com>

build: Upgrade to Go1.15

---

README.md

Signed-off-by: Iain Anderson <iain@iotechsys.com>
Build instructions refer to nonexistent make target
Issue Number: #36 
Reworded build instructions

doc: correct build instructions (#36)

---

driver/resthandler.go
driver/resthandler_test.go
go.mod

Issue Number: Fix https://github.com/edgexfoundry/device-rest-go/issues/41
upgrade device-sdk-go to v1.2.4-dev.13

build: upgrade device-sdk-go

---

cmd/res/configuration.toml
go.mod

no secure MessageBus capability
Secure MessageBus capability added

feat: Add Registry/Config Access token capability

---

Dockerfile
Dockerfile.build
go.mod
snap/hooks/install
snap/snapcraft.yaml

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
This PR updates the service to use go 1.16 (including the snap build), and also fixes a snap build breakage caused by recent build changes.

fix(build): update to go 1.16

---

Makefile
cmd/res/configuration.toml
go.mod

Latest SDK which removed shared code which forced ZMQ dependency on all services.
Added Missing InscureSecrets

refactor: Secure MessageBus Rework

---

cmd/main.go
cmd/res/configuration.toml
driver/restdriver.go
driver/resthandler.go
driver/resthandler_test.go
go.mod

refactor: bump dependency version and update import path

---

go.mod

- Update SDK to v2.0.0
- Update core-contract to v2.0.0

build: Update SDK and core-contracts lib

---

GOVERNANCE.md
OWNERS.md
cmd/res/configuration.toml
cmd/res/devices/sample-devices.toml

also added governance.md and owner.md files for LF Edge
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

fix: update all TOML to use quote and not single-quote

---

driver/resthandler.go

Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>
The code seems more difficult as it uses a double condition. In fact, one condition is always truth.
None
Checking one condition is more simple for code understanding.
Remove the condition code that is always true.

fix: remove the code: condition that is always true

---

README.md
snap/README.md
snap/hooks/pre-refresh
snap/local/hooks/Makefile
snap/local/hooks/go.mod
snap/local/hooks/go.sum
snap/snapcraft.yaml

```
git clone https://github.com/MonicaisHer/device-rest-go.git
cd device-rest-go
git checkout update-snap-package 
snapcraft --shell 
snap try prime
snap start --enable edgex-device-rest
snap install edgexfoundry --edge
snap connect edgexfoundry:edgex-secretstore-token edgex-device-rest:edgex-secretstore-token
sudo journalctl -f | grep rest
```
validated by seeing:
```
msg="Starting device-rest 2.0.1-dev.14 "
msg="device rest started"
```

build(snap): update snap package and add snap section in README

---

.golangci.yml
Makefile
driver/restdriver.go
driver/resthandler.go

addressed lint errors found in the code
Fixes #165
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
run make lint target in the Makefile

feat: enable gosec and default linter set

---

cmd/res/configuration.toml

Signed-off-by: Chris Hung <chris@iotechsys.com>

fix: add device service key in CommandRequestTopic

---

cmd/res/configuration.toml

Signed-off-by: Chris Hung <chris@iotechsys.com>

fix: update command request and response topic

---

Attribution.txt
Dockerfile
Makefile
go.mod
snap/local/helper-go/go.mod
snap/snapcraft.yaml

Run non-secure EdgeX stack with Device Virtual
Build and run service from command line
Verify logs no errors bootstrapping.

build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

---

openapi/v3/device-rest.yaml

docs: [Device REST] Add Swagger file
